spring.application.name=internshiptracker
#Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/internship_tracker_db

#Database username
spring.datasource.username=postgres

#Database password
spring.datasource.password=@0kk30123

#Hibernate DDL auto configuration
spring.jpa.hibernate.ddl-auto=update

jwt.secret=supersecuresecretkeysupersecure123
jwt.expiration=86400000